var EvaluationSubjectData = {Rows:
[
{"SubjectNo":"<a href='evaluation_student_lst.html'>S000101<a>","SubjectName":"基础","Period":"3周","StartDate":"2014-07-01","EndDate":"2014-12-01","Teacher":"<a href='evaluation_detail.html'>张三<a>","Evaluation":"<a href='evaluation_grade.html'>评价<a>","Attendance":"<a href='evaluation_attendance.html'>评价<a>"},
{"SubjectNo":"<a href='evaluation_student_lst.html'>S000102<a>","SubjectName":"模型（2阶段）","Period":"3周","StartDate":"2014-07-01","EndDate":"2014-12-01","Teacher":"<a href='evaluation_detail.html'>张三<a>","Evaluation":"<a href='evaluation_grade.html'>评价<a>","Attendance":"<a href='evaluation_attendance.html'>评价<a>"},
{"SubjectNo":"<a href='evaluation_student_lst.html'>S000103<a>","SubjectName":"室内（2阶段）","Period":"3周","StartDate":"2014-07-01","EndDate":"2014-12-01","Teacher":"<a href='evaluation_detail.html'>张三<a>","Evaluation":"<a href='evaluation_grade.html'>评价<a>","Attendance":"<a href='evaluation_attendance.html'>评价<a>"},
{"SubjectNo":"<a href='evaluation_student_lst.html'>S000104<a>","SubjectName":"室外（2阶段）","Period":"3周","StartDate":"2014-07-01","EndDate":"2014-12-01","Teacher":"<a href='evaluation_detail.html'>张三<a>","Evaluation":"<a href='evaluation_grade.html'>评价<a>","Attendance":"<a href='evaluation_attendance.html'>评价<a>"},
{"SubjectNo":"<a href='evaluation_student_lst.html'>S000105<a>","SubjectName":"后期（2阶段）","Period":"3周","StartDate":"2014-07-01","EndDate":"2014-12-01","Teacher":"<a href='evaluation_detail.html'>张三<a>","Evaluation":"<a href='evaluation_grade.html'>评价<a>","Attendance":"<a href='evaluation_attendance.html'>评价<a>"},
{"SubjectNo":"<a href='evaluation_student_lst.html'>S000106<a>","SubjectName":"动画及项目","Period":"4周","StartDate":"2014-07-01","EndDate":"2014-12-01","Teacher":"<a href='evaluation_detail.html'>张三<a>","Evaluation":"<a href='evaluation_grade.html'>评价<a>","Attendance":"<a href='evaluation_attendance.html'>评价<a>"},
{"SubjectNo":"<a href='evaluation_student_lst.html'>S000107<a>","SubjectName":"模型高级","Period":"2周","StartDate":"2014-07-01","EndDate":"2014-12-01","Teacher":"<a href='evaluation_detail.html'>张三<a>","Evaluation":"<a href='evaluation_grade.html'>评价<a>","Attendance":"<a href='evaluation_attendance.html'>评价<a>"},
{"SubjectNo":"<a href='evaluation_student_lst.html'>S000108<a>","SubjectName":"室内高级","Period":"2周","StartDate":"2014-07-01","EndDate":"2014-12-01","Teacher":"<a href='evaluation_detail.html'>张三<a>","Evaluation":"<a href='evaluation_grade.html'>评价<a>","Attendance":"<a href='evaluation_attendance.html'>评价<a>"},
{"SubjectNo":"<a href='evaluation_student_lst.html'>S000109<a>","SubjectName":"渲染高级","Period":"2周","StartDate":"2014-07-01","EndDate":"2014-12-01","Teacher":"<a href='evaluation_detail.html'>张三<a>","Evaluation":"<a href='evaluation_grade.html'>评价<a>","Attendance":"<a href='evaluation_attendance.html'>评价<a>"},
{"SubjectNo":"<a href='evaluation_student_lst.html'>S000110<a>","SubjectName":"动画（3阶段）","Period":"2周","StartDate":"2014-07-01","EndDate":"2014-12-01","Teacher":"<a href='evaluation_detail.html'>张三<a>","Evaluation":"<a href='evaluation_grade.html'>评价<a>","Attendance":"<a href='evaluation_attendance.html'>评价<a>"},
{"SubjectNo":"<a href='evaluation_student_lst.html'>S000111<a>","SubjectName":"后期（3阶段）","Period":"2周","StartDate":"2014-07-01","EndDate":"2014-12-01","Teacher":"<a href='evaluation_detail.html'>张三<a>","Evaluation":"<a href='evaluation_grade.html'>评价<a>","Attendance":"<a href='evaluation_attendance.html'>评价<a>"},
{"SubjectNo":"<a href='evaluation_student_lst.html'>S000112<a>","SubjectName":"实训","Period":"8周","StartDate":"2014-07-01","EndDate":"2014-12-01","Teacher":"<a href='evaluation_detail.html'>张三<a>","Evaluation":"<a href='evaluation_grade.html'>评价<a>","Attendance":"<a href='evaluation_attendance.html'>评价<a>"}
],Total:12};